"""sprint 1 foundation and kpi governance

Revision ID: 37f11cf88d4d
Revises: 
Create Date: 2026-08-25 23:25:10.501480
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '37f11cf88d4d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('week_start_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    op.create_table('execution_logs',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('service', sa.String(length=60), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('http_path', sa.String(length=300), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('connector', sa.String(length=40), nullable=True),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('query_count', sa.Integer(), nullable=True),
    sa.Column('query_duration_ms', sa.Integer(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_service'), ['service'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_user_id'), ['user_id'], unique=False)

    op.create_table('permissions',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('resource_label', sa.String(length=300), nullable=True),
    sa.Column('old_version', sa.String(length=40), nullable=True),
    sa.Column('new_version', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('catalog_versions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('selected_table_count', sa.Integer(), nullable=False),
    sa.Column('profiled_table_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('active_kpi_count', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'version', name='uq_catalog_version')
    )
    with op.batch_alter_table('catalog_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_versions_company_id'), ['company_id'], unique=False)

    op.create_table('company_calendars',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('week_start_day', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'calendar_key', name='uq_calendar_company_key')
    )
    with op.batch_alter_table('company_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_calendars_company_id'), ['company_id'], unique=False)

    op.create_table('company_documents',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('document_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('document_class', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('access_scope', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_key', name='uq_document_company_key')
    )
    with op.batch_alter_table('company_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_documents_company_id'), ['company_id'], unique=False)

    op.create_table('data_sources',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.String(length=160), nullable=True),
    sa.Column('schema_name', sa.String(length=160), nullable=True),
    sa.Column('username', sa.String(length=160), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('refresh_frequency', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_source_company_name')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_company_id'), ['company_id'], unique=False)

    op.create_table('kpi_definitions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'kpi_key', name='uq_kpi_company_key')
    )
    with op.batch_alter_table('kpi_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_definitions_company_id'), ['company_id'], unique=False)

    op.create_table('roles',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('role_key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_admin_role', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'role_key', name='uq_role_company_key')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_role_key'), ['role_key'], unique=False)

    op.create_table('system_events',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('company_document_versions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=600), nullable=True),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('inline_content', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['company_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_version')
    )
    with op.batch_alter_table('company_document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_document_versions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_document_versions_document_id'), ['document_id'], unique=False)

    op.create_table('company_users',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_scope', sa.JSON(), nullable=False),
    sa.Column('denied_columns', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_membership')
    )
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_users_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('source_tables',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('database_name', sa.String(length=160), nullable=True),
    sa.Column('schema_name', sa.String(length=160), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('table_type', sa.String(length=20), nullable=False),
    sa.Column('approx_row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'schema_name', 'table_name', name='uq_source_table_identity')
    )
    with op.batch_alter_table('source_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_tables_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_tables_data_source_id'), ['data_source_id'], unique=False)

    op.create_table('kpi_versions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('business_definition', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('formula_expression', sa.Text(), nullable=False),
    sa.Column('formula_spec', sa.JSON(), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=True),
    sa.Column('numerator', sa.JSON(), nullable=True),
    sa.Column('denominator', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('null_handling', sa.String(length=30), nullable=False),
    sa.Column('primary_data_source_id', sa.String(length=36), nullable=True),
    sa.Column('primary_source_table_id', sa.String(length=36), nullable=True),
    sa.Column('source_definition', sa.JSON(), nullable=False),
    sa.Column('time_field', sa.String(length=200), nullable=True),
    sa.Column('time_grain', sa.String(length=20), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('expected_baseline_method', sa.String(length=40), nullable=False),
    sa.Column('seasonality_expectation', sa.String(length=60), nullable=True),
    sa.Column('sparse_history_strategy', sa.String(length=40), nullable=False),
    sa.Column('min_history_days', sa.Integer(), nullable=True),
    sa.Column('proposal_origin', sa.String(length=20), nullable=False),
    sa.Column('discovery_evidence', sa.JSON(), nullable=False),
    sa.Column('definition_document_id', sa.String(length=36), nullable=True),
    sa.Column('definition_document_version', sa.Integer(), nullable=True),
    sa.Column('definition_source', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_version', sa.Integer(), nullable=True),
    sa.Column('last_validation_status', sa.String(length=20), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validation_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['calendar_id'], ['company_calendars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_document_id'], ['company_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpi_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_source_table_id'], ['source_tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_id', 'version', name='uq_kpi_version')
    )
    with op.batch_alter_table('kpi_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_versions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_versions_kpi_id'), ['kpi_id'], unique=False)

    op.create_table('selected_tables',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('business_alias', sa.String(length=200), nullable=True),
    sa.Column('declared_grain', sa.String(length=300), nullable=True),
    sa.Column('primary_time_column', sa.String(length=200), nullable=True),
    sa.Column('selected_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table_id', name='uq_selected_table')
    )
    with op.batch_alter_table('selected_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selected_tables_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selected_tables_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selected_tables_source_table_id'), ['source_table_id'], unique=False)

    op.create_table('source_columns',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=80), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('references_table', sa.String(length=200), nullable=True),
    sa.Column('references_column', sa.String(length=200), nullable=True),
    sa.Column('semantic_type', sa.String(length=30), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table_id', 'column_name', name='uq_source_column_identity')
    )
    with op.batch_alter_table('source_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_columns_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_columns_source_table_id'), ['source_table_id'], unique=False)

    op.create_table('source_health',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_column', sa.String(length=200), nullable=True),
    sa.Column('coverage_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coverage_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_lag_seconds', sa.Integer(), nullable=True),
    sa.Column('expected_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('freshness_status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('completeness_pct', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_health_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_health_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_health_source_table_id'), ['source_table_id'], unique=False)

    op.create_table('source_reconciliations',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('left_table_id', sa.String(length=36), nullable=False),
    sa.Column('right_table_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('left_grain', sa.String(length=300), nullable=True),
    sa.Column('right_grain', sa.String(length=300), nullable=True),
    sa.Column('left_time_grain', sa.String(length=20), nullable=True),
    sa.Column('right_time_grain', sa.String(length=20), nullable=True),
    sa.Column('shared_dimensions', sa.JSON(), nullable=False),
    sa.Column('unmapped_dimensions', sa.JSON(), nullable=False),
    sa.Column('time_overlap_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['left_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_table_id', 'right_table_id', name='uq_reconciliation_pair')
    )
    with op.batch_alter_table('source_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_reconciliations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_reconciliations_left_table_id'), ['left_table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_reconciliations_right_table_id'), ['right_table_id'], unique=False)

    op.create_table('table_grains',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=False),
    sa.Column('declared_grain', sa.String(length=300), nullable=True),
    sa.Column('inferred_grain', sa.String(length=300), nullable=True),
    sa.Column('grain_columns', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=80), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('distinct_combinations', sa.Integer(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('time_column', sa.String(length=200), nullable=True),
    sa.Column('time_grain', sa.String(length=20), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table_id', name='uq_table_grain')
    )
    with op.batch_alter_table('table_grains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_grains_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_grains_source_table_id'), ['source_table_id'], unique=False)

    op.create_table('table_profiles',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=False),
    sa.Column('profiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('profiled_column_count', sa.Integer(), nullable=False),
    sa.Column('withheld_column_count', sa.Integer(), nullable=False),
    sa.Column('withheld_columns', sa.JSON(), nullable=False),
    sa.Column('completeness_pct', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table_id', name='uq_table_profile')
    )
    with op.batch_alter_table('table_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_profiles_source_table_id'), ['source_table_id'], unique=False)

    op.create_table('table_relationships',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=False),
    sa.Column('source_column', sa.String(length=200), nullable=False),
    sa.Column('target_table_id', sa.String(length=36), nullable=False),
    sa.Column('target_column', sa.String(length=200), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=80), nullable=True),
    sa.Column('is_declared', sa.Boolean(), nullable=False),
    sa.Column('source_distinct_count', sa.Integer(), nullable=True),
    sa.Column('target_distinct_count', sa.Integer(), nullable=True),
    sa.Column('orphan_count', sa.Integer(), nullable=True),
    sa.Column('orphan_pct', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table_id', 'source_column', 'target_table_id', 'target_column', name='uq_relationship_identity')
    )
    with op.batch_alter_table('table_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_relationships_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_relationships_source_table_id'), ['source_table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_relationships_target_table_id'), ['target_table_id'], unique=False)

    op.create_table('column_profiles',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=False),
    sa.Column('source_column_id', sa.String(length=36), nullable=False),
    sa.Column('profiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('null_count', sa.Integer(), nullable=True),
    sa.Column('null_pct', sa.Float(), nullable=True),
    sa.Column('distinct_count', sa.Integer(), nullable=True),
    sa.Column('distinct_pct', sa.Float(), nullable=True),
    sa.Column('min_value', sa.String(length=300), nullable=True),
    sa.Column('max_value', sa.String(length=300), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('zero_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('blank_count', sa.Integer(), nullable=True),
    sa.Column('sample_values', sa.JSON(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('is_candidate_key', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('access_withheld', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_column_id'], ['source_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_column_id', name='uq_column_profile')
    )
    with op.batch_alter_table('column_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_profiles_source_column_id'), ['source_column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_profiles_source_table_id'), ['source_table_id'], unique=False)

    op.create_table('join_safety',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_id', sa.String(length=36), nullable=False),
    sa.Column('source_is_unique', sa.Boolean(), nullable=True),
    sa.Column('target_is_unique', sa.Boolean(), nullable=True),
    sa.Column('source_uniqueness_ratio', sa.Float(), nullable=True),
    sa.Column('target_uniqueness_ratio', sa.Float(), nullable=True),
    sa.Column('fan_out_factor', sa.Float(), nullable=True),
    sa.Column('max_fan_out', sa.Integer(), nullable=True),
    sa.Column('duplicate_key_rate', sa.Float(), nullable=True),
    sa.Column('expected_cardinality', sa.String(length=20), nullable=True),
    sa.Column('observed_cardinality', sa.String(length=20), nullable=True),
    sa.Column('safety_level', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['table_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id', name='uq_join_safety_relationship')
    )
    with op.batch_alter_table('join_safety', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_join_safety_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_join_safety_relationship_id'), ['relationship_id'], unique=False)

    op.create_table('kpi_access_policies',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('role_key', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('row_scope', sa.JSON(), nullable=False),
    sa.Column('column_scope', sa.JSON(), nullable=False),
    sa.Column('domain_scope', sa.JSON(), nullable=False),
    sa.Column('aggregate_only', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_version_id', 'role_key', name='uq_kpi_access_role')
    )
    with op.batch_alter_table('kpi_access_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_access_policies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_access_policies_kpi_version_id'), ['kpi_version_id'], unique=False)

    op.create_table('kpi_dimensions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_name', sa.String(length=120), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=True),
    sa.Column('source_table', sa.String(length=200), nullable=True),
    sa.Column('source_column', sa.String(length=200), nullable=False),
    sa.Column('hierarchy', sa.JSON(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('is_default_breakdown', sa.Boolean(), nullable=False),
    sa.Column('approx_cardinality', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_version_id', 'dimension_name', name='uq_kpi_dimension')
    )
    with op.batch_alter_table('kpi_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_dimensions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_dimensions_kpi_version_id'), ['kpi_version_id'], unique=False)

    op.create_table('kpi_drivers',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('driver_type', sa.String(length=30), nullable=False),
    sa.Column('source_table_id', sa.String(length=36), nullable=True),
    sa.Column('source_table', sa.String(length=200), nullable=True),
    sa.Column('source_column', sa.String(length=200), nullable=True),
    sa.Column('controllable', sa.Boolean(), nullable=False),
    sa.Column('measurement_method', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_version_id', 'driver_name', name='uq_kpi_driver')
    )
    with op.batch_alter_table('kpi_drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_drivers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_drivers_kpi_version_id'), ['kpi_version_id'], unique=False)

    op.create_table('kpi_lineage',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=True),
    sa.Column('data_source_name', sa.String(length=160), nullable=True),
    sa.Column('source_table_id', sa.String(length=36), nullable=True),
    sa.Column('schema_name', sa.String(length=160), nullable=True),
    sa.Column('table_name', sa.String(length=200), nullable=True),
    sa.Column('column_name', sa.String(length=200), nullable=True),
    sa.Column('transformation', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['source_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_lineage_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_lineage_kpi_version_id'), ['kpi_version_id'], unique=False)

    op.create_table('kpi_materiality_rules',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('relative_threshold_pct', sa.Float(), nullable=True),
    sa.Column('absolute_threshold', sa.Float(), nullable=True),
    sa.Column('statistical_rule', sa.String(length=120), nullable=True),
    sa.Column('business_criticality', sa.String(length=20), nullable=False),
    sa.Column('priority_policy', sa.String(length=120), nullable=True),
    sa.Column('persistence_periods', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_version_id', name='uq_kpi_materiality')
    )
    with op.batch_alter_table('kpi_materiality_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_materiality_rules_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_materiality_rules_kpi_version_id'), ['kpi_version_id'], unique=False)

    op.create_table('kpi_validation_runs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('warned_count', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_validation_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_validation_runs_kpi_version_id'), ['kpi_version_id'], unique=False)

    op.create_table('kpi_validation_checks',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('test_type', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['kpi_validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_validation_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_validation_checks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_validation_checks_kpi_version_id'), ['kpi_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_validation_checks_validation_run_id'), ['validation_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi_validation_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_validation_checks_validation_run_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_validation_checks_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_validation_checks_company_id'))

    op.drop_table('kpi_validation_checks')
    with op.batch_alter_table('kpi_validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_validation_runs_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_validation_runs_company_id'))

    op.drop_table('kpi_validation_runs')
    with op.batch_alter_table('kpi_materiality_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_materiality_rules_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_materiality_rules_company_id'))

    op.drop_table('kpi_materiality_rules')
    with op.batch_alter_table('kpi_lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_lineage_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_lineage_company_id'))

    op.drop_table('kpi_lineage')
    with op.batch_alter_table('kpi_drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_drivers_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_drivers_company_id'))

    op.drop_table('kpi_drivers')
    with op.batch_alter_table('kpi_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_dimensions_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_dimensions_company_id'))

    op.drop_table('kpi_dimensions')
    with op.batch_alter_table('kpi_access_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_access_policies_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_access_policies_company_id'))

    op.drop_table('kpi_access_policies')
    with op.batch_alter_table('join_safety', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_join_safety_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_join_safety_company_id'))

    op.drop_table('join_safety')
    with op.batch_alter_table('column_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_profiles_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_column_profiles_source_column_id'))
        batch_op.drop_index(batch_op.f('ix_column_profiles_company_id'))

    op.drop_table('column_profiles')
    with op.batch_alter_table('table_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_relationships_target_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_relationships_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_relationships_company_id'))

    op.drop_table('table_relationships')
    with op.batch_alter_table('table_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_profiles_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_profiles_company_id'))

    op.drop_table('table_profiles')
    with op.batch_alter_table('table_grains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_grains_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_grains_company_id'))

    op.drop_table('table_grains')
    with op.batch_alter_table('source_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_reconciliations_right_table_id'))
        batch_op.drop_index(batch_op.f('ix_source_reconciliations_left_table_id'))
        batch_op.drop_index(batch_op.f('ix_source_reconciliations_company_id'))

    op.drop_table('source_reconciliations')
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_health_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_source_health_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_health_company_id'))

    op.drop_table('source_health')
    with op.batch_alter_table('source_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_columns_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_source_columns_company_id'))

    op.drop_table('source_columns')
    with op.batch_alter_table('selected_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selected_tables_source_table_id'))
        batch_op.drop_index(batch_op.f('ix_selected_tables_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_selected_tables_company_id'))

    op.drop_table('selected_tables')
    with op.batch_alter_table('kpi_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_versions_kpi_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_versions_company_id'))

    op.drop_table('kpi_versions')
    with op.batch_alter_table('source_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_tables_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_tables_company_id'))

    op.drop_table('source_tables')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_company_users_company_id'))

    op.drop_table('company_users')
    with op.batch_alter_table('company_document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_document_versions_document_id'))
        batch_op.drop_index(batch_op.f('ix_company_document_versions_company_id'))

    op.drop_table('company_document_versions')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_system_events_company_id'))

    op.drop_table('system_events')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_key'))
        batch_op.drop_index(batch_op.f('ix_roles_company_id'))

    op.drop_table('roles')
    with op.batch_alter_table('kpi_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_definitions_company_id'))

    op.drop_table('kpi_definitions')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_company_id'))

    op.drop_table('data_sources')
    with op.batch_alter_table('company_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_documents_company_id'))

    op.drop_table('company_documents')
    with op.batch_alter_table('company_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_calendars_company_id'))

    op.drop_table('company_calendars')
    with op.batch_alter_table('catalog_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_versions_company_id'))

    op.drop_table('catalog_versions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_key'))

    op.drop_table('permissions')
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_service'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_company_id'))

    op.drop_table('execution_logs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))

    op.drop_table('companies')
    # ### end Alembic commands ###
