"""detection engine: comparison configuration and detection runs

Two tables, matching the separation the engine depends on: a company's approved
comparison policy (which past days are comparable) and the persisted result of
each evaluation (actual, expected, deviation, status, and the evidence behind
them). No table, column or default here names a company, a weekday or an event --
those live in the JSON a company configures.

Revision ID: 495cfc3af89a
Revises: 37f11cf88d4d
Create Date: 2026-08-29 07:17:29.206712
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '495cfc3af89a'
down_revision: str | None = '37f11cf88d4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_bucket_configs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('config_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kpi_key', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('buckets', sa.JSON(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('min_reference_points', sa.Integer(), nullable=True),
    sa.Column('max_reference_points', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_document_version_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_model', sa.String(length=120), nullable=True),
    sa.Column('extraction_notes', sa.Text(), nullable=True),
    sa.Column('proposed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['company_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'config_key', 'version', name='uq_bucket_config_company_key_version')
    )
    with op.batch_alter_table('company_bucket_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_bucket_configs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_bucket_configs_kpi_key'), ['kpi_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_bucket_configs_status'), ['status'], unique=False)

    op.create_table('detection_runs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_definition_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_version_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_key', sa.String(length=80), nullable=False),
    sa.Column('kpi_name', sa.String(length=200), nullable=False),
    sa.Column('kpi_version', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('time_grain', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('deviation_absolute', sa.Float(), nullable=True),
    sa.Column('deviation_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comparison_label', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('bucket_applied', sa.String(length=30), nullable=False),
    sa.Column('buckets_applied', sa.JSON(), nullable=False),
    sa.Column('bucket_config_id', sa.String(length=36), nullable=True),
    sa.Column('bucket_config_key', sa.String(length=80), nullable=True),
    sa.Column('bucket_config_version', sa.Integer(), nullable=True),
    sa.Column('bucket_signature', sa.JSON(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('reference_dates', sa.JSON(), nullable=False),
    sa.Column('reference_values', sa.JSON(), nullable=False),
    sa.Column('median_value', sa.Float(), nullable=True),
    sa.Column('mad', sa.Float(), nullable=True),
    sa.Column('dispersion_basis', sa.String(length=40), nullable=True),
    sa.Column('modified_z_score', sa.Float(), nullable=True),
    sa.Column('z_threshold', sa.Float(), nullable=True),
    sa.Column('tolerance_pct', sa.Float(), nullable=True),
    sa.Column('tolerance_absolute', sa.Float(), nullable=True),
    sa.Column('breached_tolerance', sa.Boolean(), nullable=False),
    sa.Column('statistically_significant', sa.Boolean(), nullable=False),
    sa.Column('yoy_applied', sa.Boolean(), nullable=False),
    sa.Column('yoy_adjustment_factor', sa.Float(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('executed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_config_id'], ['company_bucket_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_definition_id'], ['kpi_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_version_id'], ['kpi_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_runs_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_runs_kpi_definition_id'), ['kpi_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_runs_kpi_version_id'), ['kpi_version_id'], unique=False)
        batch_op.create_index('ix_detection_runs_lookup', ['company_id', 'kpi_version_id', 'target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_runs_target_date'), ['target_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_runs_target_date'))
        batch_op.drop_index(batch_op.f('ix_detection_runs_status'))
        batch_op.drop_index('ix_detection_runs_lookup')
        batch_op.drop_index(batch_op.f('ix_detection_runs_kpi_version_id'))
        batch_op.drop_index(batch_op.f('ix_detection_runs_kpi_definition_id'))
        batch_op.drop_index(batch_op.f('ix_detection_runs_executed_at'))
        batch_op.drop_index(batch_op.f('ix_detection_runs_company_id'))

    op.drop_table('detection_runs')
    with op.batch_alter_table('company_bucket_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_bucket_configs_status'))
        batch_op.drop_index(batch_op.f('ix_company_bucket_configs_kpi_key'))
        batch_op.drop_index(batch_op.f('ix_company_bucket_configs_company_id'))

    op.drop_table('company_bucket_configs')
    # ### end Alembic commands ###
